tmaqn2b/controllers/auth.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user
from flask import Blueprint, request, redirect, render_template, url_for

from tmaqn2b.model.users import User
from tmaqn2b.model.forms import RegForm
from tmaqn2b import login_manager

auth = Blueprint('auth', __name__)

@login_manager.user_loader
def load_user(user_id):
    return User.getUserById(user_id)


@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegForm()
    if request.method == 'POST':
        if form.validate():
            existing_user = User.getUser(email=form.email.data)
            if not existing_user:
                hashpass = generate_password_hash(form.password.data, method='pbkdf2:sha256')
                User.createUser(email=form.email.data,password=hashpass, name=form.name.data)
                return redirect(url_for('auth.login'))
            else:
                form.email.errors.append("User already existed")
                render_template('register.html', form=form, panel="Register")
    return render_template('register.html', form=form, panel="Register")

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = RegForm()
    if request.method == 'POST':
        print(request.form.get('checkbox'))
        if form.validate():
            check_user = User.getUser(email=form.email.data)
            if check_user:
                if check_password_hash(check_user['password'], form.password.data):
                    login_user(check_user)
                    return redirect(url_for('book_bp.show_books'))      
                else:
                    form.password.errors.append("User Password Not Correct")
            else:
                form.email.errors.append("No Such User")
    return render_template('login.html', form=form, panel="Login")

@auth.route('/logout', methods = ['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('book_bp.show_books'))

tmaqn2b/controllers/bookController.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from tmaqn2b.model.books import Book
from tmaqn2b.model.forms import BookForm

bp = Blueprint('book_bp', __name__) 

@bp.route('/')
@bp.route('/booktitles', methods=['GET'])
def show_books():
    if Book.objects.count() == 0:
        Book.save_books()
    all_books = Book.get_all_books()
    selected_category = request.args.get('category', 'All')

    sorted_books = sorted(all_books, key=lambda book: book['title'])
    
    if selected_category != 'All':
        filtered_books = [
            book for book in sorted_books 
            if book['category'] == selected_category
        ]
    else:
        filtered_books = sorted_books
        
    return render_template(
        'books.html', 
        books=filtered_books, 
        panel='Book Titles',
        selected_category=selected_category
    )

@bp.route('/bookdetails', methods=['GET'])
def show_details():
    book_title = request.args.get('title')
    selected_book = Book.get_book_by_title(book_title)
    
    if selected_book is None:
        return redirect(url_for('book_bp.show_books')) 

    return render_template(
        'books_details.html',
        book=selected_book,
        panel='Book Details'
    )

@bp.route('/newbook', methods=['GET', 'POST'])
def new_book():
    form = BookForm()
    if request.method == 'POST':
        if form.validate():
            existing_book = Book.get_book_by_title(form.title.data)
            if not existing_book:
                authors= []

                if form.author_1.data:
                    if form.is_illustrator_1.data:
                        authors.append(f"{form.author_1.data} (Illustrator)")
                    else:
                        authors.append(form.author_1.data)

                if form.author_2.data:
                    if form.is_illustrator_2.data:
                        authors.append(f"{form.author_2.data} (Illustrator)")
                    else:
                        authors.append(form.author_2.data)
                
                if form.author_3.data:
                    if form.is_illustrator_3.data:
                        authors.append(f"{form.author_3.data} (Illustrator)")
                    else:
                        authors.append(form.author_3.data)

                if form.author_4.data:
                    if form.is_illustrator_4.data:
                        authors.append(f"{form.author_4.data} (Illustrator)")
                    else:
                        authors.append(form.author_4.data)
                    
                if form.author_5.data:
                    if form.is_illustrator_5.data:
                        authors.append(f"{form.author_5.data} (Illustrator)")
                    else:
                        authors.append(form.author_5.data)

                book = Book.create_book(
                    genres=form.genres.data,
                    title=form.title.data,
                    category=form.category.data,
                    url=form.url.data,
                    description=form.description.data.splitlines(),
                    authors=authors,
                    pages=form.pages.data,
                    available=form.copies.data,
                    copies=form.copies.data
                )
                flash(f'{book.title} added successfully!', 'success')
                return redirect(url_for('book_bp.new_book'))
            else:
                form.title.errors.append("Book with this title already exists.")
    return render_template('new_book.html', form=form, panel="Add New Book")

tmaqn2b/controllers/loanController.py
from flask import Blueprint, render_template, url_for, redirect, flash
from flask_login import login_required, current_user
from tmaqn2b.model.loans import Loan
from tmaqn2b.model.books import Book
from tmaqn2b.model.users import User
from random import randint
from datetime import date, timedelta

loan_bp = Blueprint('loan_bp', __name__)


def generate_date(a: date, add_days: bool) -> date: 
    random_td = timedelta(days=randint(10, 20))
    
    if add_days:
       
        if a >= date.today() - timedelta(days=10):
            return date.today()
        
        
        return date.today() + random_td
    else:
        
        return a - random_td


@loan_bp.route('/loans')
def display_loans():
    if current_user.is_authenticated:
        user_loans = Loan.objects(member=current_user.id).order_by('-borrowDate')
        return render_template(
            'loans.html',
            all_loans=user_loans,
            panel='Current Loans',
        )
    else:
        flash("Please login or register first to get an account", "error")
        return redirect(url_for('auth.login'))
        

@loan_bp.route('/loans/renew_loan/<book_title>', methods=['POST'])
def renew_loan(book_title):
    
    loan = Loan.getLoanbyBook(current_user.email, book_title)
    
    new_borrowDate = generate_date(loan.borrowDate, True)
    loan.renewLoan(new_borrowDate)
    flash(f"{loan.book.title} loan has been renewed.", "success")
    return redirect(url_for('loan_bp.display_loans'))


@loan_bp.route('/loans/return_loan/<book_title>', methods=['POST'])
def return_loan(book_title):
    
    loan = Loan.getLoanbyBook(current_user.email, book_title)
    return_date = generate_date(loan.borrowDate, True)
    loan.returnLoan(return_date)
    flash(f"{loan.book.title} loan has been returned", "success")
    return redirect(url_for('loan_bp.display_loans'))



@loan_bp.route('/loans/delete_loan/<book_title>', methods=['POST'])
def delete_loan(book_title):
    
    loan = Loan.getLoanbyBook(current_user.email, book_title)
    loan.deleteLoan()
    flash(f"{loan.book.title} loan has been deleted.", "success")
        
    return redirect(url_for('loan_bp.display_loans'))


@loan_bp.route('/make_loan/<book_title>', methods=['GET'])
def make_loan(book_title):
    if current_user.is_authenticated:
        book = Book.get_book_by_title(book_title)
        borrowDate = generate_date(date.today(), False)
        loan = Loan.createLoan(current_user, book, borrowDate, 0)
        if loan:
            flash(f"{loan.book.title} has been loaned.", "success")
        else:
            flash("Error creating loan", "error")
        return redirect(url_for("book_bp.show_books"))
    else:
        flash("Please login or register first to get an account", "error")
        return redirect(url_for('auth.login'))

tmaqn2b/templates/_render_field.html
{% macro render_field(field) %}
<div class="form-group">
    <label for="{{ field.id }}">{{ field.label }}</label>
    {{ field(class="form-control", **kwargs) | safe }}
    {% if field.errors %}
        {% for error in field.errors %}
            <span class="text-danger">{{ error }}</span>
        {% endfor %}
    {% endif %}
</div>
{% endmacro %}


{% macro render_book_field(field) %}

<div class="form-group">
    <div class="row">
        <div class="col-2">
            <label for="{{ field.name }} ">
                <strong>{{ field.label.text.capitalize() }}</strong>
            </label>
        </div>
        <div class="col-10">
            {{ field(class_='form-control', **kwargs)|safe }}
        </div>
    </div>
    <ul>
        {% for error in field.errors %}
        <li style="color:red;">{{ error }}</li>
        {% endfor %}
    </ul>
</div>
{% endmacro %}

{% macro render_author_field(author, illustrator) %}

<div class="form-group">
    <div class="row">
        <div class="col-2">
            <label for="{{ author.name }} ">
                <strong>{{ author.label.text.capitalize() }}</strong>
            </label>
        </div>
        <div class="col-7">
            {{ author(class_='form-control', **kwargs)|safe }}
        </div>
        <div class="col-1">
            {{ illustrator(class_='form-control', **kwargs)|safe }}
        </div>
        <div class="col-2">
            <label for="{{ illustrator.name }} ">
                <p>{{ illustrator.label.text.capitalize() }}</p>
            </label>
        </div>
    </div>
    <ul>
        {% for error in author.errors %}
        <li style="color:red;">{{ error }}</li>
        {% endfor %}
    </ul>
</div>
{% endmacro %}

tmaqn2b/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
    integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
    integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/all.js"
    integrity="sha384-xymdQtn1n3lH2wcu0qhcdaOpQwyoarkgLVxC/wZ5q7h9gHtxICrpcaSUfygqZGOe"
    crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/custom.css')}}">
  <title>SG Library - {{ panel }}</title>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-light">
    <button class="navbar-toggler ml-auto mb-2 bg-light" type="button" data-toggle="collapse" data-target="#myNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="myNavbar">
      <div class="container-fluid">
        <div class="row">
          <div class="col-xl-2 col-lg-3 col-md-4 sidebar fixed-top">
            <a href="#" class="navbar-brand text-white d-block mx-auto text-center py-3 mb-4 bottom-border">SG Library</a>
            {% if current_user.is_authenticated  %}
            <span class="text-center text-white d-block py-3 mb-4 bottom-border">
              {{ current_user.name }}
            </span>
            {% endif %}
            <ul class="navbar-nav flex-column mt-4">
              <li class="nav-item">
                <a href="{{ url_for('book_bp.show_books') }}" class="nav-link text-white p-3 mb-2 current"><i class="fas fa-address-card fa-lg mr-3"></i>Book Titles</a>
              </li>
              {% if current_user.is_authenticated and current_user.email != "admin@lib.sg" %}
              <li class="nav-item">
                <a href="{{ url_for('loan_bp.display_loans') }}" class="nav-link text-white p-3 mb-2 sidebar-link"><i class = "fas fa-clipboard fa-lg mr-3"></i>Loans</a>
              </li>
              {% endif %}
              {% if current_user.email == "admin@lib.sg" %}
              <li class="nav-item">
                <a href="{{ url_for('book_bp.new_book') }}" class="nav-link text-white p-3 mb-2 sidebar-link"><i class="fas fa-cloud-upload-alt fa-lg mr-3"></i>Add New Book</a>
              </li>
              {% endif %}
              {% if not current_user.is_authenticated %}
              <li class="nav-item">
                <a href="{{ url_for('auth.login') }}" class="nav-link text-white p-3 mb-2 sidebar-link"><i class="fas fa-sign-in-alt fa-lg mr-3"></i>Login</a>
              </li>
              <li class="nav-item">
                <a href="{{ url_for('auth.register') }}" class="nav-link text-white p-3 mb-2 sidebar-link"><i class="fas fa-user fa-lg mr-3"></i>Register</a>
              </li>
              {% endif %}
            </ul>
          </div>
          <!--End of Sidebar-->
          <!--Top Navbar-->
          <div class="col-xl-10 col-lg-9 col-md-8 ml-auto bg-dark fixed-top py-2 top-navbar">
            <div class="row align-items-center">
              <div class="col-md-4">
                <h4 class="text-light text-uppercase mb-0">{{ panel }}</h4>
              </div>
              {% if current_user.is_authenticated %}
              <div class="col-md-8">
                <ul class="navbar-nav">
                  <li class="nav-item ml-auto"><a href="#" class="nav-link" data-toggle="modal"
                      data-target="#sign-out"><i class="fas fa-sign-out-alt fa-lg"></i></a></li>
                </ul>
              </div>
              {% endif %}
            </div>
          </div>
          <!--End of Top Navbar-->
        </div>
      </div>
    </div>
  </nav>
  
  <!-- modal -->
  <div class="modal fade" id="sign-out">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Want to leave?</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          Press logout to leave
        </div>
        <div class="modal-footer">
          <form action='/logout' method='GET'>
            <button type="button" class="btn btn-success" data-dismiss="modal">Stay Here</button>
            <button type="submit" class="btn btn-danger" href="{{ url_for('auth.logout') }}">Logout</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- end of modal -->


  <!--cards-->
  <section>
    <div class="container-fluid">
      <div class="row">
        <div class="col-xl-10 col-lg-9 col-md-8 ml-auto px-0">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            <div class="row">
              <div class="col-12">
                {% for category, message in messages %}
                  <div class="alert alert-{{ 'success' if category == 'success' else 'danger' }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                {% endfor %}
              </div>
            </div>
            {% endif %}
          {% endwith %}
        
          {% block filter_bar %}
          {% endblock %}

          {% block mainblock %}
          {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--end of cards-->
</body>

</html>

tmaqn2b/templates/books.html
{% extends "base.html" %}

{% block filter_bar %}
<form action="/booktitles" method="GET"> 
<div class="row mx-md-5 mb-4 border rounded shadow-sm filter_bar"> 
  <div class="col-12 p-3"> 
    <div class="d-flex align-items-center justify-content-between">
      
      <p class="mb-0">Number of titles: {{ books | length }}</p>
      
      <div class="d-flex align-items-center">
        <p class="mb-0 me-4 p-1">Category</p>
        <select class="form-select me-3" name="category" style="width: 150px; height: 40px;">
          <option value="All" {% if selected_category == 'All' %}selected{% endif %}>All</option>
          <option value="Children" {% if selected_category == 'Children' %}selected{% endif %}>Children</option>
          <option value="Teens" {% if selected_category == 'Teens' %}selected{% endif %}>Teens</option>
          <option value="Adult" {% if selected_category == 'Adult' %}selected{% endif %}>Adult</option>
        </select>
        <button class="btn btn-success" type="submit">Search</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block mainblock %}
  {% for book in books %}
  <div class="row mb-3 p-5 border rounded bg-white mx-md-5 card-common"> 
      <div class="col-md-2 text-center">
          <img src="{{ book.url }}" alt="{{ book.title }} cover" class="img-fluid rounded">
      </div>
      
      <div class="col-7 col-md-10 d-flex flex-column"> 
          
          <h3 class="mt-0 mb-2"><strong>{{ book.title }}</strong></h3>
          <h3 class="mb-3"><strong> {{ book.authors | join(", ") }}</strong></h3>
                
          <h5>
              Category: {{ book.category }}, 
              {% if book.genres %}
              {{ book.genres | join(", ") }}
              {% else %}
              No Genres
              {% endif %}
          </h5>
          <p class="mb-4">Pages: {{ book.pages }}</p>

          {% if book.description|length > 0 %}
          <p>{{ book.description[0] }}</p>
          {% endif %}

          {% if book.description|length > 1 %}
          <p>{{ book.description[-1] }}</p>
          {% endif %}
          <div class="align-self-end btn-flush-right mx-md-5 p-5 d-flex flex-row ">
              {% if book.available and current_user.email != "admin@lib.sg" %}
              <a href="{{ url_for('loan_bp.make_loan', book_title=book.title) }}" class="btn btn-success mx-1">Make a Loan</a>
              {% endif %}
              <a href="{{ url_for('book_bp.show_details', title=book.title) }}" class="btn btn-success">More details</a>
          </div>
      </div>
    </div>
  {% endfor %}
</form>
{% endblock %}

tmaqn2b/templates/books_details.html
{% extends "base.html" %}

{% block mainblock %}
<div class="row">
    <div class="col-12 p-3">
        <div class="row mb-3 p-5 border rounded bg-white mx-md-5 card-common"> 
            
            <div class="col-md-2 text-center">
                <img src="{{ book.url }}" alt="{{ book.title }} cover" class="img-fluid rounded">
            </div>
            
            <div class="col-10 d-flex flex-column"> 
                
                <h3 class="mt-0 mb-2"><strong>{{ book.title }}</strong></h3>
                <h3 class="mb-3"><strong> {{ book.authors | join(", ") }}</strong></h3>
                
                <h5>
                    Category: {{ book.category }}, 
                    {% if book.genres %}
                    {{ book.genres | join(", ") }}
                    {% else %}
                    No Genres
                    {% endif %}
                </h5>
                
                <p class="mb-1">Pages: {{ book.pages }}</p>
                <p class="mb-4"><strong>Copies:</strong> {{ book.copies }} <strong>Available:</strong> {{ book.available }}</p>
                
                {% for paragraph in book.description %}
                <p>{{ paragraph }}</p>
                {% endfor %}
                
                <div class="align-self-end btn-flush-right mx-md-5">
                    {% if book.available and current_user.email != "admin@lib.sg" %}
                    <a href="{{ url_for('loan_bp.make_loan', book_title=book.title) }}" class="btn btn-success mx-1">Make a Loan</a>
                    {% else %}
                    <button class="btn btn-danger mx-1 disabled">Not Available</button>
                     {% endif %}
                    <a href="{{ url_for('book_bp.show_books') }}" class="btn btn-success">Back to Book Titles</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tmaqn2b/templates/loans.html
{% extends "base.html" %}

{% block mainblock %}

{% if not all_loans %}
<h2>
    No loan currently
</h2>
{% else %}
<div class="card my-2 shadow">
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Title/Author</th>
                    <th scope="col">Borrow Date</th>
                    <th scope="col">Return Date</th>
                    <th scope="col">Renew Count</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for loan in all_loans %}
                <tr>
                    {% if loan.book %}
                        <td>
                            <img class="img-fluid loan-book-cover" src="{{ loan.book.url }}" alt="{{ loan.book.title }} cover" style="max-height: 100px;">
                            <br>
                            <strong>{{ loan.book.title }}</strong>
                            <br>
                            By {{ loan.book.authors | join(', ')  }}
                        </td>
                        <td>
                            {{ loan.borrowDate.strftime('%Y-%m-%d') }}
                        </td>
                        <td>
                            {% if loan.returnDate %} 
                                {{ loan.returnDate.strftime('%Y-%m-%d') }} 
                            {% else %}
                                Currently Out
                            {% endif %}
                        </td>
                        <td>{{ loan.renewCount }}</td>
                        {% if loan.returnDate %}
                            <td>
                                <form method="POST" action="{{ url_for('loan_bp.delete_loan', book_title=loan.book.title) }}">
                                    <button type="submit" class="btn btn-danger text-light">Delete</button>
                                </form>
                            </td>
                            <td></td>
                        {% elif loan.is_overdue() or loan.renewCount >= 2 %}
                            <td>
                                <form method="POST" action="{{ url_for('loan_bp.return_loan', book_title=loan.book.title) }}">
                                    <button type="submit" class="btn btn-success text-light">Return</button>
                                </form>
                            </td>
                            <td></td>
                        {% else %}
                            <td>
                                <form method="POST" action="{{ url_for('loan_bp.return_loan', book_title=loan.book.title) }}">
                                    <button type="submit" class="btn btn-success text-light">Return</button>
                                </form>
                            </td>
                            <td>
                                <form method="POST" action="{{ url_for('loan_bp.renew_loan', book_title=loan.book.title) }}">
                                    <button type="submit" class="btn btn-success text-light">Renew</button>
                                </form>
                            </td>
                        {% endif %} 
                        {% endif %}
                </tr>
                {% endfor %} 
            </tbody>
        </table>
    </div>
</div>
{% endif %}
{% endblock %}

tmaqn2b/templates/login.html
{% extends "base.html" %}

{% from '_render_field.html' import render_field %}
{% block mainblock %}
<div class="col-xl-6 col-sm-4 p-2">
  <div class="card card-common">
  <div class="card-header">
    <h2>Login</h2>
  </div>
  <div class="card-body">
      <form action="/login" method="post">
          {{ render_field(form.email, type="email", placeholder="Enter email", id="email") }}
          {{ render_field(form.password, type="password", placeholder="Enter password", id="pwd") }}
          {{ form.hidden_tag() }}
          <div>
            <label class="col-md-4">
              <input type="checkbox" name="checkbox" value="1"> Remember Me
            </label>
          </div>
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-success", value="login">Submit</button>
          </div>
      </form>
  </div>
</div>
<div>
{% endblock %}

tmaqn2b/templates/new_book.html
{% from "_render_field.html" import render_book_field, render_author_field %}
{% extends "base.html" %}

{% block mainblock %}
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class=flashes>
    {% for category, message in messages %}
      <li class="alert alert-{{ 'success' if category == 'success' else 'danger' }}" role="alert">
        {{ message }}
      </li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

<div class="card my-2 shadow">
    <div class="card-body">
        <form action="{{ url_for('book_bp.new_book') }}" method="post">
            {{ render_book_field(form.genres, type="genres", id="genres") }}
            {{ render_book_field(form.title, type="title", id="title") }}
            {{ render_book_field(form.category, type="category", id="category") }}
            {{ render_book_field(form.url, type="url", id="url") }}
            {{ render_book_field(form.description, type="description", id="description") }}
            {{ render_author_field(form.author_1, form.is_illustrator_1) }}
            {{ render_author_field(form.author_2, form.is_illustrator_2) }}
            {{ render_author_field(form.author_3, form.is_illustrator_3) }}
            {{ render_author_field(form.author_4, form.is_illustrator_4) }}
            {{ render_author_field(form.author_5, form.is_illustrator_5) }}
            {{ render_book_field(form.pages, type="pages", id="pages") }}
            {{ render_book_field(form.copies, type="copies", id="copies") }}
            {{ form.hidden_tag() }}
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-success", value="login">Submit</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

tmaqn2b/templates/register.html
{% extends "base.html" %}
{% from '_render_field.html' import render_field %}

{% block mainblock %}
<div class="col-xl-8 col-sm-4 p-2">
  <div class="card card-common">
    <div class="card-header">
      <h2>Register</h2>
    </div>
    <div class="card-body">
      <form action="/register" method="post">
        {{ render_field(form.email, type="email", placeholder="Enter email", id="email") }}
        {{ render_field(form.password, type="password", placeholder="Enter password", id="pwd") }}
        {{ render_field(form.name, type="name", id="name") }}
        {{ form.hidden_tag() }}
        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-success" , value="login">Submit</button>
        </div>
        
      </form>
    </div>
  </div>
</div>
{% endblock %}